import { NextPage } from 'next';
import Head from 'next/head';
import SignUpTemplate from '../components/templates/signUpTemplate';
import { ToastContainer } from 'react-toastify';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<SignUpTemplate />
			<ToastContainer
				position='top-left'
				autoClose={5000}
				hideProgressBar={false}
				newestOnTop={false}
				closeOnClick
				rtl={false}
				pauseOnFocusLoss
				draggable
				pauseOnHover
				theme='dark'
			/>
		</>
	);
};

export default Home;
