import { styled } from '@stitches/react';
import { NextPage } from 'next';
import Head from 'next/head';
import Form from '../components/organisms/form';
import SignUpTemplate from '../components/templates/signUpTemplate';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
			</Head>
			<SignUpTemplate />
		</>
	);
};

export default Home;
