import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { BackgroundBox, BackgroundGlobeFull, Box, Button, Stack, Text } from '../styles'

const Home: NextPage = () => {
  return (
    // <div>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //     <link rel="preconnect" href="https://fonts.googleapis.com" />
    //     <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='crossorigin' />
    //     <link
    //       href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
    //       rel="stylesheet" />
    //   </Head>
    //   <h1>Teste frontend</h1>
    // </div>

    <>
      <Head>
        <title>Intrabank | Desafio Frontend</title>
        <meta name="description" content="Desafio Frontend Intrabank" />
      </Head>
      <BackgroundGlobeFull />
      <BackgroundBox media={{
        "@initial": "sm",
        "@md": "md",
        "@xl": "xl",
      }}>
        <Box usage={"box"}>
          <Stack size={"large"} media={"sm"}>
            <Text
              size={"large"}
              weight={"heavy"}
            >👋</Text>

            <Text
              size={"medium"}
              weight={"heavy"}
            >
              Desafio Frontend
            </Text>


            <Text
              size={"small"}
              weight={"light"}
            >
              Olá, eu me chamo <Text as="span" weight={"heavy"}>Rômulo Takaoka</Text> e esse é o meu projeto para o <Text as="span" weight={"heavy"}>Desafio Frontend Intrabank</Text>.
            </Text>

            <Text
              size={"small"}
              weight={"light"}
            >
              Para acessar o Formulário de Cadastro, basta clicar no botão abaixo. ⬇️
            </Text>

            <Link href="/cadastro">
              <Button as="button">
                Cadastrar-se
              </Button>
            </Link>

          </Stack>
        </Box>
      </BackgroundBox>
    </>
  )
}

export default Home

