import { NextPage } from "next";
import Head from "next/head";

const Register: NextPage = () => {

  const handleSubmit = (event: React.FormEvent): void => {
    event.preventDefault();

    const target = event.target as typeof event.target & {
      firstName: { value: string };
      lastName: { value: string };
      email: { value: string };
      birthday: { value: Date };
      password: { value: string };
      country: { value: string };
      bio: { value: string };
      receiveNotifications: { checked: boolean };
    }

    console.log(
      `Cadastro realizado com sucesso.
      Nome: ${target.firstName.value}
      Sobrenome: ${target.lastName.value}
      E-mail: ${target.email.value}
      Data de nascimento: ${target.birthday.value}
      Senha: ${target.password.value}
      País: ${target.country.value}
      Bio: ${target.bio.value}
      Recebe notificações? ${target.receiveNotifications.checked}
      `)
  }

  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='crossorigin' />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet" />
      </Head>
      <main>
        <h1>Cadastre-se</h1>
        <p>Para começar, insira os dados abaixo:</p>

        <form onSubmit={handleSubmit}>

          <label htmlFor="firstName">
            Nome
            <input
              type="text"
              id="firstName"
              name="firstName"
              placeholder="Nome" />
          </label>
          <br />

          <label htmlFor="lastName">
            Sobrenome
            <input
              type="text"
              id="lastName"
              name="lastName"
              placeholder="Sobrenome" />
          </label>
          <br />

          <label htmlFor="email">
            E-mail
            <input
              type="email"
              id="email"
              name="email"
              placeholder="E-mail" />
          </label>
          <br />

          <label htmlFor="birthday">
            Data de nascimento
            <input
              type="date"
              id="birthday"
              name="birthday"
              placeholder="Data de nascimento" />
          </label>
          <br />

          <label htmlFor="password">
            Senha
            <input
              type="password"
              id="password"
              name="password"
              placeholder="Senha" />
          </label>
          <br />

          <label htmlFor="countries">
            Selecione seu país
            <select id="countries" name="country">
              <option value="br">Brasil</option>
              <option value="us">Estados Unidos</option>
              <option value="jp">Japão</option>
              <option value="au">Austrália</option>
            </select>
          </label>
          <br />

          <label htmlFor="bio">
            Bio
            <textarea
              name="bio"
              id="bio"
              cols={30}
              rows={5}>
            </textarea>
          </label>
          <br />

          <input type="submit" value="Cadastrar" />

          <label htmlFor="receiveNotifications">
            Desejo receber notificações
            <input
              type="checkbox"
              id="receiveNotifications"
              name="receiveNotifications" />
          </label>

        </form>

      </main>
    </>
  )
}

export default Register