import { NextPage } from "next";
import Head from "next/head";
import { Form } from "../../components/form";
import { styled } from "../../stitches.config";

const Text = styled('p', {})

const Register: NextPage = () => {


  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Text as={"h1"}>Cadastre-se</Text>
        <p>Para começar, insira os dados abaixo:</p>
        <Form />

      </main>
    </>
  )
}

export default Register